version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
      
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      
  spark:
    build:
      context: .
      dockerfile: Dockerfile-spark
    depends_on:
      - kafka
    ports:
      - "4040:4040"
    command: /bin/bash
    stdin_open: true
    tty: true
# version: '3'

# services:
#   zookeeper:
#     build:
#       context: .
#       dockerfile: Dockerfile-zookeeper
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181

#   kafka:
#     build:
#       context: .
#       dockerfile: Dockerfile-kafka
#     depends_on:
#       - zookeeper
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#   spark:
#     build:
#       context: .
#       dockerfile: Dockerfile-spark
#     depends_on:
#       - kafka